SUSE/salt-netapi-client

src/main/java/com/suse/saltstack/netapi/client/SaltStackConnection.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackHttpClientConnection.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackJDKConnection.java
This makes writing 
```java 
SaltStackTokenResult result = connectionFactory.create("/login", config).getResult(Integer.class, json.toString())
```
a compile time error instead of a runtime error.
=> Make resultType stricter to catch errors at compile time

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java
At the moment, the methods in SaltStackClient are called like the salt netapi endpoints they are connecting to. If this method naming scheme is followed, at some point we well have overloaded methods of the same names calling their netapi endpoints with POST and GET respectively. While this will work, because the method signatures will be different, it's highly unintuitive if the users of our library do not know the netapi (and I think they shouldn't be expected to). 
So, a simple question in a short pull request: would you consider a different, more descriptive naming scheme for these methods, and shield the user of this library from the details of the salt netapi, or was this a deliberate decision?
=> Use descriptive method name, not API endpoint

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackHttpClientConnection.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackRequestFactory.java, src/main/java/com/suse/saltstack/netapi/config/SaltStackClientConfig.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/config/SaltStackClientConfigTest.java
This replaces the current stringly typed `SaltStackClientConfig` with a statically typed key/value store that knows the type of each key. This shifts the burden of parsing the configuration values from the consumers side to the producers side. So everything querying the config for values does not have to deal with parsing and error handling of invalid values like `"hello"` as a port value. This also results in those invalid values being detected earlier (for example when the config is loaded from a file instead of when a value is used).
I would also suggest to generally make parameters stricter and ask for what is really needed instead of something that could potentially be parsed to what is needed. An example of this is the change …
=> Make working with the SaltStackClientConfig more typesafe

.gitignore
Intellij also puts `.iml` files in sub directories if they are configured as modules (for example having `main` and `test` configures as separate modules).
=> Ignore all .iml files

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackHttpClientConnection.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackJDKConnection.java, src/main/java/com/suse/saltstack/netapi/exception/SaltStackParsingException.java, src/main/java/com/suse/saltstack/netapi/parser/SaltStackParser.java, src/main/java/com/suse/saltstack/netapi/utils/SaltStackClientUtils.java, src/test/java/com/suse/saltstack/netapi/config/SaltStackClientConfigTest.java, src/test/java/com/suse/saltstack/netapi/utils/SaltStackClientUtilsTest.java
- Code cleanup such as removing extra semicolon, redundant or unused variables, incorrect exception throw specifications and unnecessary boxing for primitive integer type.
- Add missing Javadoc and remove incorrect ones.
=> Code and Javadoc cleanup

src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/main/java/com/suse/saltstack/netapi/results/Token.java, src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java, src/test/resources/login_response_wrong_date.json
This patch adds dates to login token. For parsing dates, new
deserializer was added to SaltStackParser class.
=> Add 'start' and 'expire' dates to token

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
- Add asynchronous support for all implemented requests. Allows one to specify an Executor but defaults to Executors.newCachedThreadPool() if none is given.
- Java 7 compatible (not using Java 8 new concurrent features).
- Add testing for asynchronous requests. ```ant run-tests``` clean.
=> Add asynchronous support for all implemented requests

build.xml
At least on Ubuntu 14.04 when running ant ```run-tests``` the following error is printed on the test reports:
```
junit/framework/JUnit4TestAdapterCache
java.lang.NoClassDefFoundError: junit/framework/JUnit4TestAdapterCache
```
This does not happen on Ubuntu 14.10.
According to [1] and [2] it's a classpath problem. Adding ```fork="yes"``` to ```<junit>``` tag on build.xml solves the problem for both Ubuntu 14.04 and 14.10 (and probably others as well). This option tells ant to run tests on a separate JVM [3], hopefully with correct JUnit jars on classpath.
[1] real-logic/simple-binary-encoding#96
[2] https://lists.debian.org/debian-java/2013/06/msg00086.html
[3] http://ant.apache.org/manual/Tasks/junit.html
=> Add option fork=yes to <junit> tag on build.xml to avoid classpath problems

src/main/java/com/suse/saltstack/netapi/client/Connection.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/client/impl/HttpClientConnection.java, src/main/java/com/suse/saltstack/netapi/client/impl/JDKConnection.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
The `startCommand()` methods return opaque job ids. These commits introduce a new client methods `queryJobResult()`, which enable querying for the results of those jobs.
The `Connection` class was extended by one method, enabling the creation of `GET` requests.
=> Add possibility to query for job results

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/Applications.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/HttpServer.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/Request.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/ServerThread.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/Stats.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java, src/test/resources/stats_response.json
This PR implements access to the netapi `/stats` endpoint. I couldn't find any documentation on the return type of this call so all the datatypes are "best guess" implementations based on the `json` returned by my local saltmaster. I also left the `Request` field of `cherrypy.Applications` unimplemented and added a todo since the `json` only contains an empty object so i don't know it's structure.
* `getBindAddress` could return `InetSocketAddress` instead of a `String`
* Exposing `getThreads` feels redundant since `getWorkerThreads().size()` should give the same information.
* `Uptime` could be represented with `java.time.Duration` when we move to Java 8.
* Redundant information like in `threads` /  `workerThreads` and `uptime` / `startTime` / `currentTime` could be checked against each …
=> /stats endpoint implementation

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/utils/ClientUtils.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/utils/ClientUtilsTest.java, src/test/resources/minions_request.json
This fixes #49 and adjusts the test to make sure everything works as expected.
One thing to note here is that we pass the arguments all arguments (positional and named) as `json` strings. At first i thought that would be a problem but after some tests is looks like the server is fine with it and parses the strings to the type of the argument and uses them as expected.
=> Fix: send kwargs properly to the netapi and adjust tests

checkstyle.xml, pom.xml, src/main/java/com/suse/saltstack/netapi/config/ClientConfig.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/config/ClientConfigTest.java, src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java, src/test/java/com/suse/saltstack/netapi/utils/ClientUtilsTest.java
This PR fixes #52. Additionally the 2 other commits enhance the checkstyle rules by making the `NewlineAtEndOfFile` rule system independent and adding a rule that complains about trailing whitespace.
=> Checkstyle enhancements

pom.xml
This makes the maven warnings go away and the encoding no longer dependent on the platform.
=> Fix maven warnings

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/datatypes/Keys.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java, src/test/resources/keys_response.json
This PR implements the basic `/keys` endpoint with no parameters. There are 3 more endpoints related to key management which will be part of separate PRs once i figure out the details.
=> Implement keys endpoint with no parameters.

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/datatypes/Arguments.java, src/main/java/com/suse/saltstack/netapi/datatypes/Job.java, src/main/java/com/suse/saltstack/netapi/datatypes/JobMinions.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java, src/test/resources/jobs_response.json, src/test/resources/jobs_response_args_as_kwargs.json, src/test/resources/jobs_response_kwargs.json, src/test/resources/jobs_response_multiple_kwarg.json
...by parsing responses to GET request on '/jobs' resource.
- The 'Job' datatype was renamed to more meaningful 'JobMinions'
datatype.
- New datatype 'Job' was created into which the '/jobs' resource is
parsed.
- Added corresponding parser and parser test.
=> Add support for querrying jobs

src/main/java/com/suse/saltstack/netapi/client/impl/HttpClientConnection.java, src/main/java/com/suse/saltstack/netapi/exception/SaltUserUnauthorizedException.java
request() method in HttpClientConnection was way too long (69 lines), so I decided to refactor it into more smaller methods to make it clearer and abstract away implementation details down in the individual methods.
=> Refactor HttpClientConnection into shorter methods

src/main/java/com/suse/saltstack/netapi/datatypes/Job.java, src/main/java/com/suse/saltstack/netapi/exception/ParsingException.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/resources/jobs_response_invalid_start_time.json, src/test/resources/jobs_response_null_start_time.json
Adds start time to Job class.
Salt JobIds are made from the date and time when the job was created (example from today - May 3, 2015: 20150503195439947382). Unfortunately, Salt Master does not use UTC when constructing these Id's, meaning the master's current time zone is used which is unknown to the minion and so it gets lost when translating the JobId into a StartTime.
One could argue that it would be easier to just parse the JobId instead of the strange date format that cherrypy returns, but I don't think we should rely on JobId's having this format forever.
It would be much better if cherrypy returned a timestamp instead. That would mean that the minion can translate the date and time into it's own time zone. Parsing would also be easier and more reliable.
=> Add job start time to Job class

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/config/ClientConfig.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/Applications.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/HttpServer.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/Request.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/ServerThread.java, src/main/java/com/suse/saltstack/netapi/datatypes/cherrypy/Stats.java
This pull request contains some javadoc related general cleanup and fixes that I did after reviewing the [v0.1.0 javadocs] (http://suse.github.io/saltstack-netapi-client-java/apidocs/). The fixes are mostly about the `SaltStackClient` class:
- use `<p>` to structure method descriptions
- use the @code annotation to format the API endpoints
- remove some @link annotations as return and parameter types are linked anyway
- add missing @return annotations, fix typos, etc.
The javadocs can be generated in your workspace using:
mvn javadoc:javadoc
=> Javadoc cleanup and fixes

.travis.yml, README.md, scripts/publish_javadoc.sh
This is a first draft for the automatic publishing of `javadocs` to `gh-pages`.
This will (or at least should) publish the `master` branch at `gh-pages/docs/master` and
`tags` at `gh-pages/docs/<TAG>`.
I tested it on my fork and it seems to work fine but i would really appreciate if you could review this carefully since i'm pretty bad at writing `bash` scripts.
=> Add automagic javadoc publishing for tags and master

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/resources/logout_response.json
This patch should fix the `logout()` and `logoutAsync()` methods to actually perform a POST request. Recently we accidentally sent a GET request here since the `data` passed in to `create()` was `null`. The proposed patch is just a quick fix, we might want to reconsider the behaviour of the `create()` method that does actually create a GET request whenever the given data is `null`.
Further this pull request adds missing unit tests for `logout()` and `logoutAsync()` and the example response (`logout_response.json`) has been fixed.
This fixes issue #64.
=> Fix logout to actually perform a POST request

src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java, src/test/resources/login_response_missing_date.json
TypeAdapters are stream-oriented and more memory effecient than
(tree-based) Deserializers.
=> Replace SaltStackDateDeserializer with DateAdapter

pom.xml
This is the remaining changes to pom.xml needed to deploy artifacts into maven central (via [OSSRH staging repositories] (http://central.sonatype.org/pages/releasing-the-deployment.html#login-into-ossrh)). This should help us to close #72 with the next release.
=> Preparations for releasing to maven central

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/datatypes/target/Glob.java, src/main/java/com/suse/saltstack/netapi/datatypes/target/MinionList.java, src/main/java/com/suse/saltstack/netapi/datatypes/target/NodeGroup.java, src/main/java/com/suse/saltstack/netapi/datatypes/target/Target.java, src/main/java/com/suse/saltstack/netapi/utils/ClientUtils.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/utils/ClientUtilsTest.java, src/test/resources/minions_request.json, src/test/resources/run_request.json
This is a remake of #87 with some fixes on top.  Adds initial support for `expr_form` which addresses #82.
Here is @lucidd's original snippet that can be used for testing:
```java
SaltStackClient client = new SaltStackClient(URI.create("http://172.17.0.19:8000"));
client.getConfig().put(ClientConfig.SOCKET_TIMEOUT, 0);
Map<String, Object> result =  client.run("salt", "", AuthModule.AUTO, "local",
new NodeGroup("min123"), "test.ping", new ArrayList<>(), new HashMap<>());
result.forEach((key, value) -> {
System.out.println(key + " -> " + value);
});
Token token = client.login("salt", "", AuthModule.AUTO);
ScheduledJob job = client.startCommand(new MinionList("minion1", "minion4"), "test.ping",
new ArrayList<>(), new HashMap<>());
System.out.println("Job ID: "+ job.getJid()); …
```
=> Support expr_form in run() and startCommand()

src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/java/com/suse/saltstack/netapi/config/ClientConfigTest.java, src/test/java/com/suse/saltstack/netapi/utils/ClientUtilsTest.java
The correct order is assertEquals(expected, actual) and some unit
tests were using reverse order. Using incorrect order makes any test
failure messages somewhat confusing.
=> Correct order of some unit tests assertEquals() parameters

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/main/java/com/suse/saltstack/netapi/results/ResultInfo.java, src/main/java/com/suse/saltstack/netapi/results/ResultInfoSet.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/resources/jobs_response_pending.json, src/test/resources/run_response.json
These two patches attempt to address the "pending job" enhancement (#83)
The first patch simply adds capability to parse the `info` structure. This structure contains duplicate minion result set. I've included a convenience function to return result set in the same format as the old `return` structure.
The second patch replaces old job result and returns ResultInfoSet instead of a simple map. The simple map is still available from within the ResultInfo class.
=> Improve job result handling

src/main/java/com/suse/saltstack/netapi/datatypes/Event.java, src/main/java/com/suse/saltstack/netapi/event/EventListener.java, src/main/java/com/suse/saltstack/netapi/event/EventStream.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/event/TyrusWebSocketEventsTest.java, src/test/java/com/suse/saltstack/netapi/event/WebSocketServerSalt.java
This patch brings in basic parsing of events into objects. So far we are only separating an event's `tag` from its `data` though. This is already very helpful in order to filter the event stream for interesting events. Apart from that there is two small commits affecting the event stream tests. Please have a look, @lucidd, thank you!
=> Basic parsing of events

src/main/java/com/suse/saltstack/netapi/calls/modules/Status.java
This patch adds support for using the functions from the [`salt.modules.status` module] (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.status.html) with the `callSync`/`callAsync` interfaces. All functions are represented in the new class, the only one I left out is [`master()`] (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.status.html#salt.modules.status.master), which I was not sure if it makes sense to be called via the API.
I tested all of the return types manually, but they are still very generic for many functions. This can definitely be improved in terms of parsing the data into more specialized objects.
=> Add support for salt.modules.status

src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
Moved SimpleDateFormat from static variable to local variable inside the
method they are used, because DateFormats are not thread-safe, meaning that
they maintain an internal representation of state. Using them in a static
context can yield some pretty strange bugs if multiple threads access the
same instance simultaneously.
Reference:
https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html#synchronization
=> SimpleDateFormat from static variable to local

src/main/java/com/suse/saltstack/netapi/event/EventListener.java, src/main/java/com/suse/saltstack/netapi/event/EventStream.java, src/test/java/com/suse/saltstack/netapi/event/TyrusWebSocketEventsTest.java
This patch makes it easier to debug the websocket based event stream by passing on the [CloseReason] (http://docs.oracle.com/javaee/7/api/javax/websocket/CloseReason.html) to all event listeners whenever the event stream has closed.
=> On event stream closure, pass the CloseReason on to the listeners

src/main/java/com/suse/saltstack/netapi/calls/runner/Jobs.java, src/main/java/com/suse/saltstack/netapi/datatypes/Job.java, src/main/java/com/suse/saltstack/netapi/datatypes/StartTime.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/main/java/com/suse/saltstack/netapi/results/ResultInfo.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
This attempts to add TimeZone configuration support for master's StartTime parsing. By default, if TimeZone is unset and left as system default, there should be no performance impact.
To facilitate per-server timezone settings, parser needs to be aware of configuration. It appears that annotations are unworkable in this scenario because Gson uses reflection to to create instance for annotated types and these do not have access to JsonParser instance. No JsonParser instance, no configuration, no timezones. I've added a simple StartTime wrapper class to remove need for annotations. External API is not affected.
There appears to be no way around rebuilding a parser though. But this only affects users that have different timezone from server (master), which I'd expect to be mostly desktop …
=> Add timezone support for parsing StartTime

pom.xml
wiremock is pulling in slf4j as its dependency in unit tests, but
because it does not pull in any logging implementation, wiremock's
logs end up in /dev/null.
...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
...
Adding a JDK logging backend for slf4j gives us wiremock logs.
=> Add dependency on slf4j-jdk14 logger

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/config/ClientConfig.java, src/main/java/com/suse/saltstack/netapi/event/EventStream.java, src/main/java/com/suse/saltstack/netapi/exception/MessageTooBigException.java, src/test/java/com/suse/saltstack/netapi/event/TyrusWebSocketEventsTest.java
This patch adds support for buffering partial websocket messages in `EventStream` by implementing [`MessageHandler.Partial`] (http://docs.oracle.com/javaee/7/api/javax/websocket/MessageHandler.Partial.html). A configurable limit on the allowed message length is introduced that can be disabled by setting a value less than or equal to 0. Partial messages will be buffered and listeners get notified only when the last message has been received. The stream will be closed with a suitable [`CloseReason`] (http://docs.oracle.com/javaee/7/api/javax/websocket/CloseReason.html) if the buffer grows beyond the maximum length.
This is what you get without this patch using Tomcat as client and receiving a "big" event:
```
Event stream closed: The decoded text message was too big for the output buffer …
```
=> Buffer partial websocket messages

src/main/java/com/suse/saltstack/netapi/calls/modules/Match.java
This implements some of the functions in the match Module
=> implement Match module functions

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/event/EventStream.java, src/test/java/com/suse/saltstack/netapi/event/TyrusWebSocketEventsTest.java
This patch allows to add event listeners to the websocket based event stream before the stream will actually be initialized. This way we can be sure that we won't miss any events between the handshake and adding the listener, which especially helps to make the unit tests more stable (see `TyrusWebSocketEventsTest`).
=> Allow adding event listeners before stream initialization

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java, src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java, src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java, src/test/resources/jobs_run_response.json, src/test/resources/run_response.json
Fixed parsing for `cmd.run` (new versions of Saltstack should only return "A dictionary with the result 
of the execution, keyed by minion ID. A compound command will return a sub-dictionary 
keyed by function name.").
Adjusting parser accordingly.
Fix #126
=> Fix run json

src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
Some tests were using the same exact code to check/validate results.
Refactor: extract method, make it private, rewrite test.
All tests are passing.
=> Refactor SaltStackClientTest

src/main/java/com/suse/saltstack/netapi/calls/LocalCall.java, src/main/java/com/suse/saltstack/netapi/calls/RunnerCall.java, src/main/java/com/suse/saltstack/netapi/calls/WheelCall.java, src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java
There is no logic changes. The only major change is that the generic
SaltStackClient.call() function is now exposed as a public function.
Issue: #99 
As always, comments are welcome.
=> Move sync/async remote call setups to their respective classes

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/calls/SaltSSHConfig.java, src/main/java/com/suse/salt/netapi/calls/modules/State.java, src/main/java/com/suse/salt/netapi/results/SSHResult.java, src/main/java/com/suse/salt/netapi/results/StateApplyResult.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/java/com/suse/salt/netapi/examples/SaltSSH.java, src/test/resources/ssh_ping_request.json, src/test/resources/ssh_ping_response.json
This patch adds support for calling `LocalCall` instances synchronously via `salt-ssh`. The results of calls to `state.apply` were further refined to be parsed into the new type `State.ApplyResult` that contains the changes unparsed as `JSONElement`.
=> Synchronous module calls via salt-ssh

src/main/java/com/suse/salt/netapi/calls/modules/Zypper.java
registerrelease is not always sent so it should be Optional.
=> Make registerrelease Optional

src/main/java/com/suse/salt/netapi/calls/Client.java, src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/datatypes/Batch.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/java/com/suse/salt/netapi/datatypes/BatchTest.java, src/test/resources/call_sync_batch_ping_request.json, src/test/resources/call_sync_batch_ping_response.json, src/test/resources/call_sync_ping_request.json, src/test/resources/call_sync_ping_response.json
Fixes #84 
Refactored some code in LocalCall because callSync and callSyncBatch
used nearly the same logic. They now both use a helper function called
callSyncBatchable.
Added a test for callSyncBatch that checks the request body. Also added
a test for callSync that checks the request body to ensure it is not
accidentally using batching when calling callSyncBatchable.
=> Added local_batch support with tests.

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/calls/SaltSSHConfig.java, src/main/java/com/suse/salt/netapi/calls/SaltSSHUtils.java, src/main/java/com/suse/salt/netapi/client/SaltClient.java, src/main/java/com/suse/salt/netapi/parser/JsonParser.java, src/main/java/com/suse/salt/netapi/results/SSHRawResult.java, src/test/java/com/suse/salt/netapi/client/SaltClientTest.java, src/test/resources/ssh_raw_run_request.json, src/test/resources/ssh_raw_run_response.json
Current implementation for `salt-ssh` raw command execution lacks the parameter for launching the command.
This PR implements "raw shell" command execution for `salt-ssh` in another method which will be used for raw command only.
Reference: https://docs.saltstack.com/en/latest/topics/ssh/#raw-shell-calls
=> Add support for `raw_shell` commands via salt-ssh

src/main/java/com/suse/salt/netapi/client/impl/HttpClientConnection.java
Allow subclasses of `HttpClientConnection` to further customize the `HttpClientBuilder` as needed.
=> Allow additional configuration of the `HttpClientConnection`

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/datatypes/target/Glob.java, src/main/java/com/suse/salt/netapi/datatypes/target/MinionList.java, src/main/java/com/suse/salt/netapi/datatypes/target/SSHTarget.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/java/com/suse/salt/netapi/examples/SaltSSH.java
Salt ssh has a limited set of target types it can handle (compared to normal salt) see https://docs.saltstack.com/en/latest/topics/ssh/#targeting-with-salt-ssh.
Due to this its currently possible to call salt ssh in our netapi library with parameters that will not work.
The plan is to only accept target types that salt ssh can handle.
One way to achieve this would be an additional marker interface that is only implemented by targets that can be used with salt ssh.
=> Prevent wrong target types from being passed to salt ssh

src/main/java/com/suse/salt/netapi/calls/modules/Status.java
Hi,
Status.uptime was not working. https://github.com/SUSE/salt-netapi-client/issues/179
I removed the human_readable argument, as it was reported invalid. Changed the return type from Float to String.
Stefan
=> status.uptime was not working

src/main/java/com/suse/salt/netapi/calls/modules/Config.java, src/main/java/com/suse/salt/netapi/results/ModuleRun.java, src/main/java/com/suse/salt/netapi/results/OldNew.java
This adds initial support for the `config` execution module as well as some result types for other salt calls. @mateiw and @lucidd, should we merge this for 0.10.0?
=> Support for config.get and additional result types

src/main/java/com/suse/salt/netapi/calls/runner/Jobs.java
This patch enables users to receive job metadata from `Info` objects as they are returned by `jobs.list_job`. There is three different getters as in [`JobReturnEvent`](https://github.com/SUSE/salt-netapi-client/blob/master/src/main/java/com/suse/salt/netapi/event/JobReturnEvent.java#L98-L126).
=> Allow to get metadata from Jobs.Info

src/main/java/com/suse/salt/netapi/calls/modules/Schedule.java, src/test/java/com/suse/salt/netapi/calls/modules/ScheduleTest.java
The Java built in [`DateTimeFormatter.ISO_LOCAL_DATE_TIME`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE_TIME) seems to keep the fraction of seconds while it was actually supposed to cut it off. This patch should fix a bug resulting in the following error on the Salt minion side:
```
2017-03-28 16:51:33,963 [salt.utils.schedule][ERROR   ][11430] Date string could not be parsed: 2017-03-28T17:51:29.182, %Y-%m-%dT%H:%M:%S
```
=> Fix date format for Schedule (bsc#1034465)

src/main/java/com/suse/salt/netapi/calls/RunnerCall.java, src/test/resources/async_via_event_list_job_request.json
using kwarg's' as keyword seems to be wrong and is not working anymore with salt 2016.11.4 .
It works with older versions but maybe only by accident. Using 'kwarg' seems to work with old and new versions.
Maybe somebody can check this with salt. The docs are not that clear.
=> fix sending kwarg in payload in RunnerCall

src/main/java/com/suse/salt/netapi/calls/RunnerCall.java, src/main/java/com/suse/salt/netapi/calls/WheelCall.java, src/test/java/com/suse/salt/netapi/calls/runner/JobsTest.java, src/test/java/com/suse/salt/netapi/calls/wheel/KeyTest.java, src/test/java/com/suse/salt/netapi/examples/Wheel.java, src/test/resources/runner/list_job_response.json, src/test/resources/runner/list_job_unparseable_date_response.json, src/test/resources/runner/salt_exception_response.json
In case of exception where parser is unable to translate response into a proper type, show the original response from Salt.
Related issues #190
=> Better error handling in Runner and Wheel calls

src/main/java/com/suse/salt/netapi/calls/AbstractCall.java, src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/calls/RunnerCall.java, src/main/java/com/suse/salt/netapi/calls/WheelCall.java, src/main/java/com/suse/salt/netapi/utils/ClientUtils.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/java/com/suse/salt/netapi/utils/ClientUtilsTest.java
LocalCall uses 'kwarg' parameter while RunnerCall and WheelCall use 'kwargs'(with s ), during last PR i renamed 'kwarg' parameter to 'kwargs' parameter and extracted that parameter in a parent class which was wrong and caused some issues. I have reverted those changes back. Code can definitely be improved further but my lack of Salt knowledge and right now being on holidays is kind of hindrance for the time being.
Related discussion can be seen in  #193 . Main goal of this PR was issue #149.
=> Refactored some code and added module name information to Call classes

src/main/java/com/suse/salt/netapi/config/ClientConfig.java
It should be longer than the defaults in Salt (15 seconds) so you won't get timeout exceptions with the default settings (see #184).
=> Increase the default SOCKET_TIMEOUT to 20 seconds

src/main/java/com/suse/salt/netapi/parser/XorTypeAdapterFactory.java
Currently XorTypeAdapterFactory assumes the left side of the type is always a SaltError - that is currently the case but prevents using more complex Xor types, when returned data from Salt might come in different
'structures'.
This allows XorTypeAdapterFactory to work with any generic Xor type.
=> Allow use of XorTypeAdapter for general Xor types

src/main/java/com/suse/salt/netapi/client/impl/HttpClientConnection.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/java/com/suse/salt/netapi/calls/wheel/KeyTest.java, src/test/java/com/suse/salt/netapi/client/SaltClientTest.java
This changes the encoding charset for our json payload from `ISO_8859_1` to `UTF-8`
=> Use utf8 encoding for the json payload

src/main/java/com/suse/salt/netapi/calls/SaltSSHConfig.java, src/main/java/com/suse/salt/netapi/calls/SaltSSHUtils.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/resources/ssh_ping_request.json
This PR enables `randomThinDir` as parameter for the `SaltSSHConfig` builder. This new parameter will be mapped as salt-ssh `rand_thin_dir` option.
Using a random directory to deploy the salt-thin is needed on SUSE Manager to avoid a race condition when multiple "salt-ssh" calls are made using `wipe=True` and using the default "thin_dir".
Extra information included on the bug report: https://bugzilla.suse.com/show_bug.cgi?id=1055338
=> Allow using randomly generated directory to deploy salt-thin

src/main/java/com/suse/salt/netapi/calls/runner/Event.java, src/test/java/com/suse/salt/netapi/calls/runner/EventTest.java, src/test/java/com/suse/salt/netapi/examples/Runner.java, src/test/resources/runner/event_send_request.json, src/test/resources/runner/event_send_response.json
This patch adds support for the [event runner module](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.event.html) that allows to send custom events on the Salt event bus. There is also some example code showing how to call runner modules using the library.
=> Support salt.runners.event + example code

src/main/java/com/suse/salt/netapi/client/impl/RequestFactory.java
For JDK9 `javax.xml.bind` is [deprecated to be removed](https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html) in a future version. Now as JDK8 finally includes Base64 encoding and decoding we should make use of that in order to avoid having to add an additional external library in the future.
=> Do not depend on javax.xml.bind any longer

README.md, checkstyle.xml
This patch increases the checkstyle maximum line length to 120 characters.
=> Increase max line length to 120

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/client/SaltClient.java, src/main/java/com/suse/salt/netapi/datatypes/target/AbstractTarget.java, src/main/java/com/suse/salt/netapi/datatypes/target/Compound.java, src/main/java/com/suse/salt/netapi/datatypes/target/DictionaryTarget.java, src/main/java/com/suse/salt/netapi/datatypes/target/Glob.java, src/main/java/com/suse/salt/netapi/datatypes/target/Grains.java, src/main/java/com/suse/salt/netapi/datatypes/target/GrainsRegEx.java, src/main/java/com/suse/salt/netapi/datatypes/target/IPCidr.java, src/main/java/com/suse/salt/netapi/datatypes/target/MinionList.java, src/main/java/com/suse/salt/netapi/datatypes/target/NodeGroup.java, src/main/java/com/suse/salt/netapi/datatypes/target/Pillar.java, src/main/java/com/suse/salt/netapi/datatypes/target/PillarExact.java, src/main/java/com/suse/salt/netapi/datatypes/target/PillarRegEx.java, src/main/java/com/suse/salt/netapi/datatypes/target/Range.java, src/main/java/com/suse/salt/netapi/datatypes/target/RegEx.java, src/main/java/com/suse/salt/netapi/datatypes/target/Target.java, src/main/java/com/suse/salt/netapi/datatypes/target/TargetType.java, src/test/java/com/suse/salt/netapi/datatypes/target/TargetTypesTest.java
This PR addresses #103 by adding support for the following target types:
- pcre
- grain_pcre
- pillar
- pillar_exact
- pillar_pcre
- range
- compound
- ipcidr
It also adds support for special delimiters (other than `:`) in grain and pillar targets, and their variants.
=> Support additional target types

pom.xml, src/test/java/com/suse/salt/netapi/calls/CallAsyncEventsTest.java
This patch updates the gson library to a recent version, the version we used seems to be from late 2014! More recent versions bring interesting new features like [alternate serialized names](https://static.javadoc.io/com.google.code.gson/gson/2.8.2/com/google/gson/annotations/SerializedName.html#alternate--) which could be really helpful for implementing compatibility with different versions of an API.
=> Update gson library to recent version

src/main/java/com/suse/salt/netapi/event/EngineEvent.java, src/test/java/com/suse/salt/netapi/event/EngineEventTest.java
Adding engine event class and its test handling both master and minion engine events.
=> Engine events

src/main/java/com/suse/salt/netapi/calls/modules/State.java
This patch adds support for the `test` parameter on calls to `state.apply`, allowing to run states in test-only (dry-run) mode (see the [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.apply)).
=> Support the test parameter on state.apply

src/main/java/com/suse/salt/netapi/datatypes/target/AbstractTarget.java, src/main/java/com/suse/salt/netapi/datatypes/target/Target.java, src/main/java/com/suse/salt/netapi/datatypes/target/TargetType.java, src/test/java/com/suse/salt/netapi/datatypes/target/TargetTypesTest.java, src/test/resources/async_via_event_test_ping_request.json, src/test/resources/call_sync_batch_ping_request.json, src/test/resources/call_sync_ping_request.json, src/test/resources/minions_request.json, src/test/resources/run_request.json, src/test/resources/ssh_ping_request.json, src/test/resources/ssh_raw_run_request.json
This patch is to fix #227: `expr_form` is deprecated and will be replaced with `tgt_type` everywhere.
=> Change parameter name: 'expr_form' to 'tgt_type'

src/main/java/com/suse/salt/netapi/calls/modules/Pkg.java, src/test/java/com/suse/salt/netapi/calls/modules/PkgTest.java, src/test/resources/modules/pkg/info_installed_full.json
This PR enables `Pkg.InfoInstalled` call to get all installed package versions on the minion (instead only the latest version) by introducing the `allVersions` parameter for `Pkg.InfoInstalled`.
Salt `all_versions` parameter for `pkg.info_installed` has been introduced here: https://github.com/saltstack/salt/pull/47678 (approved but not yet merged)
=> Enable "Pkg.InfoInstalled" to return all installed package versions

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/client/SaltClient.java, src/main/java/com/suse/salt/netapi/event/AbstractEventStream.java, src/main/java/com/suse/salt/netapi/event/EventListener.java, src/main/java/com/suse/salt/netapi/event/EventStream.java, src/main/java/com/suse/salt/netapi/event/WebSocketEventStream.java, src/test/java/com/suse/salt/netapi/calls/CallAsyncEventsTest.java, src/test/java/com/suse/salt/netapi/event/TyrusWebSocketEventsTest.java, src/test/java/com/suse/salt/netapi/examples/Events.java
This is a set of 5 refactorings to detach `EventStream` from its WebSocket implementation and allow alternative implementations.
This is needed in order to replace reading from WebSockets completely in Uyuni where we plan to read them from a Postgres database filled by a custom Salt Engine.
Best reviewed commit-by-commit.
=> EventStream refactoring

src/main/java/com/suse/salt/netapi/event/AbstractEventStream.java
I verified in Uyuni that the previous implementation might lead to excessive monitor contention over the list, especially since iteration (in `notifyListeners`) requires a monitor.
In the application that I am looking at, we call `notifyListeners` from multiple threads, and this results in all threads but one being blocked while the notification is in progress.
This change uses a different synchronized Collection which has an extra cost on writes but never blocks reads.
=> AbstractEventStream: use copy-on-write list implementation

src/main/java/com/suse/salt/netapi/client/SaltClient.java, src/main/java/com/suse/salt/netapi/event/WebSocketEventStream.java
This should fix #237 by removing leading slashes from API endpoints when calling `uri.resolve()`. The base URL now requires to have a trailing slash, so we add it in case it does not.
@danh-fissara, it would be great if you could give this a try so we know that it solves your problem. Thanks!
=> Enable working with API served on a sub-path

pom.xml
This patch was created to fix #240 in the first place (set the scope to `provided` for websocket-api). Further dependencies are sorted by their scope now and the default scope (`compile`) is omitted.
=> Minor cleanup of pom.xml

.travis.yml
This patch changes the travis configuration (`.travis.yml`) to build and test the code with `oraclejdk8` and `oraclejdk11`.
=> Build and run tests with oraclejdk11

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/datatypes/Batch.java, src/main/java/com/suse/salt/netapi/event/BatchStartedEvent.java, src/test/java/com/suse/salt/netapi/calls/CallAsyncEventsTest.java, src/test/resources/async_batch_via_event_test_ping_request.json
adding the batch parameter to async calls as its gonna be supported in salt with https://github.com/saltstack/salt/pull/50546
=> support local async batching

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/main/java/com/suse/salt/netapi/datatypes/Batch.java
- Add 'gather_job_timeout' parameter for presence pings performed in Salt batch mode
- Export batch parameters in the salt call
=> Add 'gather_job_timeout' parameter for presence pings performed in Salt batch mode

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/test/java/com/suse/salt/netapi/calls/CallAsyncEventsTest.java
=> properly signal no matching minions on async

src/main/java/com/suse/salt/netapi/calls/LocalCall.java
This handles the stupidity that is the random `retcode` thrown into the result in batch mode.
For more info see comments in the code.
The fix works by going over the results and for each `JsonParsingError` we encounter retry to parse it after removing the `retcode` if present.
=> handle random retcode field in batch mode

src/main/java/com/suse/salt/netapi/calls/modules/Match.java, src/test/java/com/suse/salt/netapi/calls/modules/MatchTest.java, src/test/resources/modules/match/match_output.json
- This patch also includes documentation for the methods inside
the Match module class.
- Add unit test case for the Match module
=>  Add pillar and data match modules

.travis.yml, scripts/publish_javadoc.sh
This patch is updating `.travis.yml` to build the library with `openjdk8` and `openjdk11` in Travis CI. Javadoc would always be published from the `openjdk11` build on `master` branch.
=> Use OpenJDK (8 and 11) in CI

src/main/java/com/suse/salt/netapi/parser/OptionalTypeAdapterFactory.java
Salt return empty string for non-existent grains, if user expects an Optional<object> instead, GSON cannot parse it. in such cases return Optional.empty.
=> Change empty strings to optional.empty

src/main/java/com/suse/salt/netapi/AuthModule.java
removes old modules that don't exist anymore and adds all currently documented ones.
=> bring auth modules up to date with current salt docs

src/test/java/com/suse/salt/netapi/calls/CallAsyncEventsTest.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java, src/test/java/com/suse/salt/netapi/calls/modules/CmdTest.java, src/test/java/com/suse/salt/netapi/calls/modules/FileTest.java, src/test/java/com/suse/salt/netapi/calls/modules/GitTest.java, src/test/java/com/suse/salt/netapi/calls/modules/GrainsTest.java, src/test/java/com/suse/salt/netapi/calls/modules/LocateTest.java, src/test/java/com/suse/salt/netapi/calls/modules/MatchTest.java, src/test/java/com/suse/salt/netapi/calls/modules/MinionTest.java, src/test/java/com/suse/salt/netapi/calls/modules/SaltUtilTest.java, src/test/java/com/suse/salt/netapi/calls/modules/ScheduleTest.java, src/test/java/com/suse/salt/netapi/calls/modules/SmbiosTest.java, src/test/java/com/suse/salt/netapi/calls/modules/StatusTest.java, src/test/java/com/suse/salt/netapi/calls/modules/TimezoneTest.java, src/test/java/com/suse/salt/netapi/calls/runner/EventTest.java, src/test/java/com/suse/salt/netapi/calls/runner/JobsTest.java, src/test/java/com/suse/salt/netapi/calls/wheel/KeyTest.java, src/test/java/com/suse/salt/netapi/client/SaltClientDockerTest.java, src/test/java/com/suse/salt/netapi/client/SaltClientTest.java
tests are leaking resources since for each test there is a new http client that never gets cleaned up.
=> cleanup http client after each test

src/main/java/com/suse/salt/netapi/calls/modules/Git.java, src/test/java/com/suse/salt/netapi/calls/modules/GitTest.java, src/test/java/com/suse/salt/netapi/examples/GitModule.java, src/test/resources/modules/git/git_clone_error.json, src/test/resources/modules/git/git_clone_success.json
This patch add the git-clone functionality at the git module. The patch also fix an existing bug at the git module that throws a UnsopportedOperationException.
=> Git module clone

src/main/java/com/suse/salt/netapi/calls/LocalCall.java
This patch is needed to make the current `master` branch compile in Eclipse as well as in VS Code, where apparently the same compiler is used. This is the error message that I see there:
```
Type mismatch: cannot convert from List<Map<String,Object>> to List<Map<String,Result<R>>>
```
=> Fix type mismatch error with Eclipse and VS Code

src/main/java/com/suse/salt/netapi/calls/modules/Pkg.java, src/main/java/com/suse/salt/netapi/results/PatternInfo.java, src/test/java/com/suse/salt/netapi/calls/modules/PkgTest.java, src/test/resources/modules/pkg/list_patterns.json
This PR adds support for calling `pkg.list_patterns`: https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.zypperpkg.html#module-salt.modules.zypperpkg
The `list_patterns` is only implemented by the `zypperpkg` "child" execution module of `pkg`: this is why the call returns an `Optional` map.
JUnit tests added.
=> Feat: add pkg.list_patterns call

src/main/java/com/suse/salt/netapi/parser/ResultSSHResultTypeAdapterFactory.java
This PR makes `SaltSSHError` to use `stdout` as error message in cases where the Salt SSH execution produces an error event with empty `stderr` but containing meaningful data in the `stdout`:
```json
{"uyuni-master-min-sles15.mgr.suse.de": {"stdout": "\rPassword: \nError: Wrong number of arguments!\n", "stderr": "", "retcode": 255, "id": "uyuni-master-min-sles15.mgr.suse.de", "fun": "state.apply", "jid": "20220303090427537110", "_stamp": "2022-03-03T09:04:30.263709"}}
```
We noticed this happening in some ocassions, specially when using "preflight script" on salt ssh, where `SaltSSHError` was raised without no message:
=> Use "stdout" as error message for SaltSSHError in cases where "stderr" is empty

src/main/java/com/suse/salt/netapi/results/StateApplyResult.java
This PR changes the type of StateApplyResult function name to reflect the possibility of returning null a single string value or an array of string values. This supersedes https://github.com/SUSE/salt-netapi-client/pull/296.
=> handle array of names and null

src/main/java/com/suse/salt/netapi/calls/modules/TransactionalUpdate.java
This patch adds a class for `transactional_update` module. For now, the class only contains the `reboot` method.
=> Add 'transactional_update' module

src/main/java/com/suse/salt/netapi/client/impl/HttpAsyncClientImpl.java
This PR improves the exception message when creating Salt Exception reflecting some problem in salt API.
=> Improve logging when creating salt exception

src/main/java/com/suse/salt/netapi/utils/ClientUtils.java, src/main/java/com/suse/salt/netapi/utils/ParameterizedTypeImpl.java
since this class is an internal one, it can be changed without notice. Replacing this with a simple implementation of ParameterizedType.
=> Replace the use of Gson's internal newParametrizedTypeWithOwner

.github/workflows/maven.yml, pom.xml
This PR is about updating `pom.xml` and the GitHub Actions workflow (`maven.yml`):
- Update maven plugins to their latest versions
- Update GitHub Actions to their latest versions
- Update the JDK version (from 1.8 to 11, using [`release`](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html) instead of `source` and `target`) and implementation (see [all supported distributions](https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions))
=> Update JDK and maven plugin versions

src/main/java/com/suse/salt/netapi/calls/LocalCall.java, src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java
Implement for salt LocalCall `.withExecutors()` and `.withoutExecutors()`.
=> implement withExecutors for LocalCall
