SUSE/salt-netapi-client

.gitignore

Ignore IntelliJ IDEA workspace files.

Improved .gitignore for IntelliJ IDEA

---

build.xml

Clearer separation of "main" and "test" artifacts, hopefully
better readability.
(As discussed, sorry for the delay.)

Refactor build.xml

---

README.md

Those are the style guides i gathered so far from the information on different PRs. There is probably more so feel free to leave a comment. :smile:

Add style guide information and the project title to the readme

---

src/main/java/com/suse/saltstack/netapi/Constants.java
src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java
src/main/java/com/suse/saltstack/netapi/client/impl/HttpClientConnection.java
src/main/java/com/suse/saltstack/netapi/client/impl/HttpClientConnectionFactory.java
src/main/java/com/suse/saltstack/netapi/client/impl/JDKConnection.java
src/main/java/com/suse/saltstack/netapi/client/impl/JDKConnectionFactory.java
src/main/java/com/suse/saltstack/netapi/client/impl/RequestFactory.java
src/main/java/com/suse/saltstack/netapi/datatypes/Job.java
src/main/java/com/suse/saltstack/netapi/datatypes/Token.java
src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java
src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
src/test/java/com/suse/saltstack/netapi/parser/JsonParserTest.java

As suggested in #24 this PR reorganizes and renames some files as described in the commit messages.
If there are any suggestions / improvements please let me know :smile:

Reorganize package structure

---

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java
src/main/java/com/suse/saltstack/netapi/utils/ClientUtils.java
src/test/java/com/suse/saltstack/netapi/utils/ClientUtilsTest.java

...to slightly reduce duplicated code in SaltStackClient methods.

SaltStackClient:move generating JSON to explicit method

---

README.md

Adds the "new line at the end of a file" rule since it came up multiple times in various PRs.

Update style guide in the readme

---

src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java

(sorry for repeating the same PR as #38, I accidentally closed it)
it tests SaltStackClient.startCommand(...).
the mockup result json used for the test is copied from /test/resources/minions_response.json, like other json results are embedded into the SaltStackClientTest as String.
this json seems valid, a 'salt-api 2015.2.0rc1' returns the same result structure.

add new test to SaltStackClientTest: testStartCommand()

---

src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java
src/main/java/com/suse/saltstack/netapi/client/impl/HttpClientConnection.java
src/main/java/com/suse/saltstack/netapi/client/impl/JDKConnection.java
src/main/java/com/suse/saltstack/netapi/client/impl/RequestFactory.java
src/main/java/com/suse/saltstack/netapi/config/ClientConfig.java
src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java

- Add final modifier where appropriate.
- Removed unneded ```throws SaltStackException``` from ```*Async``` methods.

Code cleanup

---

src/main/java/com/suse/saltstack/netapi/client/impl/HttpClientConnection.java
src/main/java/com/suse/saltstack/netapi/client/impl/JDKConnection.java
src/main/java/com/suse/saltstack/netapi/config/ClientConfig.java
src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java

Add a config parameter CONNECTION_TIMEOUT to set the maximum connection timeout when performing HTTP requests.

Add a config parameter CONNECTION_TIMEOUT

---

src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java
src/test/resources/run_response.json

This cleans up / simplifies the tests and addresses all the points of #43.

Cleaning up Tests 

---

.travis.yml
pom.xml
src/main/java/com/suse/saltstack/netapi/client/SaltStackClient.java

This PR switches the master branch to java 8 and introduces a few enhancements that come with that.

Change to lamda syntax for async methods

---

pom.xml

This is still work in progress but here are the initial changes to comply with the maven central publishing process.

Add information for maven central publish

---

src/main/java/com/suse/saltstack/netapi/config/ClientConfig.java
src/main/java/com/suse/saltstack/netapi/event/EventStream.java

These get rid of compiler warnings.

Trivial changes

---

src/main/java/com/suse/saltstack/netapi/calls/LocalCall.java
src/main/java/com/suse/saltstack/netapi/calls/RunnerCall.java
src/main/java/com/suse/saltstack/netapi/calls/WheelCall.java
src/main/java/com/suse/saltstack/netapi/datatypes/Arguments.java
src/test/java/com/suse/saltstack/netapi/event/TyrusWebSocketEventsTest.java

These are mostly cosmetic changes, but I hope they make the code a little bit more readable.

A few more cosmetic changes

---

checkstyle.xml
src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java

It seems to have caught 2 instances by "someone"!

Add NeedBraces check to checkstyle configuration

---

src/main/java/com/suse/saltstack/netapi/calls/modules/Pkg.java
src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java
src/test/java/com/suse/saltstack/netapi/calls/modules/PkgTest.java
src/test/resources/modules/pkg/info_installed.json

This changes the `TimeDate` of `Pkg.Info` to include timezone information to reflect @isbm recent changes in salt.

Switch Pkg.Info to use ZonedTimeDate

---

src/main/java/com/suse/saltstack/netapi/datatypes/SaltVersion.java
src/test/java/com/suse/saltstack/netapi/datatypes/SaltVersionTest.java

add SaltVersion to represent and parse salt version strings :stuck_out_tongue:

add SaltVersion to represent and parse salt version strings

---

src/main/java/com/suse/saltstack/netapi/calls/modules/Beacon.java

Add beacon module function. There is still room for improvement in providing more typed config but that  can be addressed later.

Add beacon module function

---

src/main/java/com/suse/saltstack/netapi/calls/modules/Test.java

Add test module function for gathering information about minion.

Add test module function for gathering information about minion

---

src/main/java/com/suse/saltstack/netapi/event/BeaconEvent.java
src/main/java/com/suse/saltstack/netapi/event/MinionStartEvent.java
src/main/java/com/suse/saltstack/netapi/event/ResultEvent.java

implement event parsers to help dealing with events

implement event parsers to help dealing with events

---

src/main/java/com/suse/saltstack/netapi/parser/JsonParser.java

This removes the last usage of JsonDeserializer and solves issue #75

Replace JsonDeserializer implementations with TypeAdapter

---

.gitignore

Gitignore additions

---

pom.xml
src/test/java/com/suse/saltstack/netapi/examples/Calls.java
src/test/java/com/suse/saltstack/netapi/examples/Events.java

This pull request is about providing some code examples within the project to be used as a reference for people who like to get started with the library.

Add example code

---

src/main/java/com/suse/salt/netapi/calls/modules/State.java

* add `state.apply` call that takes pillar data
* add `state.show_highstate` call

state.apply with pillar data and state.show_highstate

---

src/main/java/com/suse/salt/netapi/parser/XorTypeAdapterFactory.java
src/main/java/com/suse/salt/netapi/results/GenericSaltError.java
src/test/java/com/suse/salt/netapi/calls/modules/FileTest.java

this adds the exception information to the `GenericSaltError`

add exception information to generic salt error

---

src/main/java/com/suse/salt/netapi/calls/LocalCall.java
src/main/java/com/suse/salt/netapi/calls/modules/Cmd.java
src/main/java/com/suse/salt/netapi/calls/modules/Pkg.java
src/main/java/com/suse/salt/netapi/calls/modules/Status.java
src/main/java/com/suse/salt/netapi/calls/modules/System.java
src/main/java/com/suse/salt/netapi/calls/modules/Timezone.java
src/main/java/com/suse/salt/netapi/calls/modules/Zypper.java
src/main/java/com/suse/salt/netapi/results/CmdExecCodeAllResult.java
src/main/java/com/suse/salt/netapi/results/Ret.java
src/main/java/com/suse/salt/netapi/results/StateApplyResult.java
src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java

This patch contains some latest changes and additions to module support classes.

Module additions

---

src/main/java/com/suse/salt/netapi/calls/modules/SaltUtil.java
src/main/java/com/suse/salt/netapi/calls/runner/Jobs.java

this add the functions `jobs.list_job(s)` and `saltutil.running`

add jobs.list_job(s) and saltutil.running

---

src/main/java/com/suse/salt/netapi/calls/AbstractCall.java
src/main/java/com/suse/salt/netapi/calls/Call.java
src/main/java/com/suse/salt/netapi/calls/LocalCall.java
src/main/java/com/suse/salt/netapi/calls/RunnerCall.java
src/main/java/com/suse/salt/netapi/calls/WheelCall.java
src/main/java/com/suse/salt/netapi/utils/ClientUtils.java
src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java
src/test/java/com/suse/salt/netapi/utils/ClientUtilsTest.java

Refactored some code and added module name information to Call classes

---

src/main/java/com/suse/salt/netapi/calls/AbstractCall.java
src/main/java/com/suse/salt/netapi/utils/ClientUtils.java
src/test/java/com/suse/salt/netapi/calls/LocalCallTest.java
src/test/java/com/suse/salt/netapi/utils/ClientUtilsTest.java

A getter has been added to get just the function name by extracting it from function string( containing module and function name).  
Now there are two getters, one is getFunction() which returns the string composed of module and function name in form of module.function and other one is getFunctionName() which will return just the function name. 
Related issue #149

Getter for function name.

---

src/main/java/com/suse/salt/netapi/calls/runner/Jobs.java

This PR adds some more data in the returned types and supports start/end time optional parameters.

listJobs improvements

---

src/main/java/com/suse/salt/netapi/calls/LocalCall.java
src/test/java/com/suse/salt/netapi/examples/Calls.java

related issue: 
[Getting empty responses from a localCall.callSync #165](https://github.com/SUSE/salt-netapi-client/issues/165)

Throw exception if response is empty by invoke method callSync

---

.travis.yml
pom.xml

This pull request is supposed to add support for building the library against JDK9 (in addition to JDK8).

Build with JDK9

---

pom.xml

https://bugs.openjdk.java.net/browse/JDK-8212233

fix javadoc building for java11 and later

---

README.md
pom.xml

So we can release the fix to build with latest JDK11
Superseeds #251

Version 0.15.1

---

pom.xml

Update the version to `0.16.0-SNAPSHOT` in `pom.xml`

Change version to 0.16.0-SNAPSHOT

---

src/main/java/com/suse/salt/netapi/calls/LocalCall.java

Export batch args in sync calls to salt

Export batch args in sync calls to salt

---

README.md
pom.xml

Update the checkstyle version and changes for the next release.

Version 0.16.0

---

pom.xml

Update the version to 0.16.1-SNAPSHOT in pom.xml

Change version to 0.17.0-SNAPSHOT

---

pom.xml

Version 0.18.0-SNAPSHOT

---

src/main/java/com/suse/salt/netapi/calls/modules/Grains.java
src/main/java/com/suse/salt/netapi/calls/modules/Openscap.java
src/main/java/com/suse/salt/netapi/calls/modules/State.java
src/main/java/com/suse/salt/netapi/event/MinionStartEvent.java

This PR is a collection of additions that have accumulated at https://github.com/uyuni-project/uyuni/tree/master/java/code/src/com/suse/manager/webui/utils/salt. It should be merged right before there is a new release of this library so that at the point of release there is nothing left to migrate.

Additional methods and modules
